### ISSUE TITLE
表示順序をユーザが使いやすい観点で検討してみてはどうでしょう？

### ISSUE THREAD

**Issue by norotime** [tomsyoya/should-be-do-blogs#10]
https://github.com/tomsyoya/should-be-do-blogs/blob/95a56875a161129ca7d1d9ccbda01cd1b45b1610/app/controllers/posts_controller.rb#L8

**Comment by tomsyoya** [comment]
投稿一覧とコメントを最新版が一番上に来るように修正しました！
