### ISSUE TITLE
アソシエーションメソッドを活用して一行で記述できないか検討する

### ISSUE THREAD

**Issue by norotime** [tomsyoya/should-be-do-blogs#7]
https://github.com/tomsyoya/should-be-do-blogs/blob/95a56875a161129ca7d1d9ccbda01cd1b45b1610/app/controllers/posts_controller.rb#L26

**Comment by norotime** [comment]
@tomsyoya 参考
https://railsguides.jp/association_basics.html#has-many%E3%81%A7%E8%BF%BD%E5%8A%A0%E3%81%95%E3%82%8C%E3%82%8B%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89-collection-build-attributes

**Comment by tomsyoya** [comment]
@norotime 野呂さん
ご指摘ありがとうございます。

１点質問なのですが、修正すべきポイントが良く理解できていません。
↓この箇所をアソシエーションメソッドを使用して１行にするということでよろしいでしょうか？

```
def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    ~省略~
  end
```

**Comment by norotime** [comment]
@tomsyoya はい、その通りです！

**Comment by tomsyoya** [comment]
できました！
アソシエーションでこうかけるの、初めて知りました。便利ですね。

**Comment by norotime** [comment]
@tomsyoya たくさん使ってください！
